name: AutoPkg

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  TAG_NAME: "自动打包"
  SOFTWARE_NAME: "ldr-translate"
  VERSION: "1.6.0"

jobs:
  build-ldr-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: prepare
      run: |
        echo ${{ env.VERSION }}
        mkdir -p disk

    - name: build-gtk
      run: |
        make deb-gtk
        cp build/deb/${{ env.SOFTWARE_NAME }}-gtk.deb disk/${{ env.SOFTWARE_NAME }}-${{ env.VERSION }}-gtk.deb

    - name: build-qt
      run: |
        make deb-qt
        cp build/deb/${{ env.SOFTWARE_NAME }}-qt.deb disk/${{ env.SOFTWARE_NAME }}-${{ env.VERSION }}-qt.deb

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        prerelease: true
        draft: false
        files: |
          disk/${{ env.SOFTWARE_NAME }}-${{ env.VERSION }}-gtk.deb
          disk/${{ env.SOFTWARE_NAME }}-${{ env.VERSION }}-qt.deb
